name: Release and Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Changelog
        id: Changelog
        run: |
          tag1=$(git tag --sort version:refname | tail -n 2 | head -n 1)
          tag2=$(git tag --sort version:refname | tail -n 1)
          changelog=$(git log --pretty=oneline $tag1..$tag2)
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A' - }"
          changelog=" - ${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"

      - name: Download Artifact from Appveyor
        run: |
          wget https://ci.appveyor.com/api/projects/SeherDilek/UI-Project/artifacts/UIProject.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: asset
          path: UIProject.zip

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: UIProject.zip
          asset_name: UIProject.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Changes in this release:
            ${{ steps.Changelog.outputs.changelog }}
